[package]
name = "danila-notification-service"
version = "0.1.0"
authors = ["Danila <danila.atmakin@auto1.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.28"

futures = "0.1.24"